server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8081
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
        - id: movement-service
          uri: http://localhost:8083
          predicates:
            - Path=/movement-service/**
          filters:
            - StripPrefix=1